<?php
namespace Veles\Tests\Exceptions\Http;

use Veles\Exceptions\Http\BadRequestException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-26 at 12:00:30.
 * @group exceptions
 */
class BadRequestExceptionTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @covers          \Veles\Exceptions\Http\BadRequestException
	 * @dataProvider    constructProvider
	 *
	 * @param $errors
	 * @param $expected
	 */
	public function testConstruct($errors, $expected)
	{
		$this->expectOutputString($expected);

		new BadRequestException($errors);

		$msg = 'BadRequestException::__construct() wrong behavior!';
		$this->assertSame(400, http_response_code(), $msg);
	}

	public function constructProvider()
	{
		return [
			[
				[[
					'code' => 23,
					'field' => 'name',
					'message' => 'Not found required get-parameter name'
				]],
				'{"errors":[{"code":23,"field":"name","message":"Not found required get-parameter name"}]}'
			],
			[[], '']
		];
	}
}
