<?php
namespace Veles\Tests\Exceptions\Http;

use Veles\Exceptions\Http\ForbiddenException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-15 at 17:13:33.
 * @group exceptions
 */
class ForbiddenExceptionTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var ForbiddenException
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new ForbiddenException;
	}

	public function testConstruct()
	{
		new ForbiddenException();
		$msg = 'ForbiddenException::__construct() wrong behavior!';
		$this->assertSame(403, http_response_code(), $msg);
	}
}
