<?php
namespace Veles\Tests\Exceptions\Http;

use PHPUnit\Framework\TestCase;
use Veles\Exceptions\Http\GoneException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-14 at 13:21:46.
 *
 * @group exceptions
 */
class GoneExceptionTest extends TestCase
{
	public function testConstruct()
	{
		new GoneException;
		$msg = 'NotFoundException::__construct() wrong behavior!';
		self::assertSame(410, http_response_code(), $msg);
	}
}
