<?php
namespace Veles\Tests\Exceptions\Http;

use Veles\Exceptions\Http\HttpResponseException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-13 at 14:18:08.
 * @group exceptions
 */
class HttpResponseExceptionTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @covers  \Veles\Exceptions\Http\HttpResponseException::__construct
	 */
	public function testConstruct()
	{
		ini_set('display_errors', 1);
		ini_set('log_errors', 1);

		new HttpResponseException();

		$expected = '0';
		$actual = ini_get('display_errors');
		$msg = 'HttpResponseException::__construct() wrong behavior!';
		$this->assertSame($expected, $actual, $msg);

		$actual = ini_get('log_errors');
		$msg = 'HttpResponseException::__construct() wrong behavior!';
		$this->assertSame($expected, $actual, $msg);
	}
}
