<?php
namespace Veles\Tests\Exceptions\Http;

use Veles\Exceptions\Http\NotAllowedException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-12-25 at 17:24:55.
 * @group controllers
 */
class NotAllowedExceptionTest extends \PHPUnit_Framework_TestCase
{
	public function testConstruct()
	{
		//new NotAllowedException(new Device);
		//$msg = 'NotAllowedException::__construct() wrong behavior!';
		//$this->assertSame(405, http_response_code(), $msg);
		//
		//$expected = 'Allowed: POST';
		//$result   = '';
		//
		//foreach (xdebug_get_headers() as $header) {
		//	if (strstr($header, 'Allowed:')) {
		//		$result = $header;
		//		break;
		//	}
		//}
		//
		//$this->assertSame($expected, $result, $msg);

		$this->markTestIncomplete('This test has not been implemented yet.');
	}
}
