<?php
namespace Veles\Tests\Exceptions\Http;

use Tests\Controllers\RestApiExampleController;
use Veles\Application\Application;
use Veles\Exceptions\Http\NotAllowedException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-12-25 at 17:24:55.
 * @group controllers
 */
class NotAllowedExceptionTest extends \PHPUnit_Framework_TestCase
{
	public function tearDown()
	{
		unset($_SERVER['REQUEST_METHOD']);
	}

	public function testConstruct()
	{
		$_SERVER['REQUEST_METHOD'] = 'HEAD';

		new NotAllowedException(new RestApiExampleController(new Application));
		$msg = 'NotAllowedException::__construct() wrong behavior!';
		$this->assertSame(405, http_response_code(), $msg);

		$expected = 'Allowed: GET, POST, PUT, DELETE';
		$actual   = '';

		foreach (headers_list() as $header) {
			if (strstr($header, 'Allowed:')) {
				$actual = $header;
				break;
			}
		}

		$this->assertSame($expected, $actual, $msg);
	}
}
