<?php
namespace Veles\Tests\Exceptions\Http;

use PHPUnit\Framework\TestCase;
use Veles\Exceptions\Http\NotImplementedException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-13 at 13:54:18.
 * @group exceptions
 */
class NotImplementedExceptionTest extends TestCase
{
	public function testConstruct()
	{
		new NotImplementedException;
		$msg = 'NotImplementedException::__construct() wrong behavior!';
		self::assertSame(501, http_response_code(), $msg);
	}
}
