<?php
namespace Veles\Tests\Exceptions\Http;

use Veles\Exceptions\Http\UnprocessableException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-13 at 14:56:42.
 * @group exceptions
 */
class UnprocessableExceptionTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @covers          \Veles\Exceptions\Http\UnprocessableException
	 * @dataProvider    constructProvider
	 *
	 * @param $errors
	 * @param $expected
	 */
	public function testConstruct($errors, $expected)
	{
		$this->expectOutputString($expected);

		new UnprocessableException($errors);

		$msg = 'UnprocessableException::__construct() wrong behavior!';
		$this->assertSame(422, http_response_code(), $msg);
	}

	public function constructProvider()
	{
		return [
			[
				[[
					'code' => 25,
					'field' => 'age',
					'message' => 'Not found required get-parameter age'
				]],
				'{"errors":[{"code":25,"field":"age","message":"Not found required get-parameter age"}]}'
			],
			[[], '']
		];
	}
}