<?php
namespace Veles\Tests\Model;

use Exception;
use PHPUnit\Framework\TestCase;
use Veles\DataBase\Adapters\PdoAdapter;
use Veles\DataBase\Db;
use Veles\DataBase\DbFilter;
use Veles\DataBase\DbPaginator;
use Veles\Model\ActiveRecord;
use Veles\Model\QueryBuilder;
use Veles\Tests\DataBase\DbCopy;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-27 at 16:16:41.
 *
 * @group model
 */
class ActiveRecordTest extends TestCase
{
	protected const SQL = 'SELECT * FROM table WHERE id = ?';

	/**
	 * @var ActiveRecord
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp(): void
	{
		$this->object = new ActiveRecord;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown(): void
	{
		DbCopy::unsetAdapter();
	}

	public function testGetMap(): void
	{
		$news = new News;
		$expected = [
			'id'      => 'int',
			'title'   => 'string',
			'content' => 'string',
			'author'  => 'string'
		];
		$result = $news->getMap();
		$msg = 'ActiveRecord::getMap() returns wrong result!';
		self::assertSame($expected, $result, $msg);
	}

	/**
	 * @dataProvider getByIdProvider
	 */
	public function testGetById($id, $expected, $db_result): void
	{
		$adapter = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['row'])
			->getMock();
		$adapter->expects(self::once())
			->method('row')
			->with(static::SQL)
			->willReturn($db_result);

		$builder = $this->getMockBuilder(QueryBuilder::class)
			->onlyMethods(['getById'])
			->getMock();
		$builder->expects(self::once())
			->method('getById')
			->willReturn(static::SQL);

		Db::setAdapter($adapter);

		$news = new News;
		$news->setBuilder($builder);
		$actual = $news->getById($id);
		$msg = 'ActiveRecords::getById() returns wrong result!';
		self::assertSame($expected, $actual, $msg);

		$actual = ['id' => '', 'title' => '', 'content' => '', 'author' => ''];
		$expected = ($expected)
			? [
				'id'      => "$id",
				'title'   => "title_$id",
				'content' => "content_$id",
				'author'  => "author_$id"
			]
			: $actual;

		$news->getProperties($actual);
		$msg = 'Wrong ActiveRecords::getById() behavior!';
		self::assertSame($expected, $actual, $msg);
	}

	public function getByIdProvider(): array
	{
		$found1 = [
			'id'      => "3",
			'title'   => "title_3",
			'content' => "content_3",
			'author'  => "author_3"
		];

		$found2 = [
			'id'      => "20",
			'title'   => "title_20",
			'content' => "content_20",
			'author'  => "author_20"
		];

		$not_found = [];

		return [
			[3, true, $found1],
			[0, false, $not_found],
			[500, false, $not_found],
			[20, true, $found2]
		];
	}

	/**
	 * @dataProvider getAllProvider
	 */
	public function testGetAll($data, $expected): void
	{
		$adapter = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['rows', 'getFoundRows'])
			->getMock();
		$adapter->expects(self::once())
			->method('rows')
			->willReturn($data);

		Db::setAdapter($adapter);

		$pager = new DbPaginator('paginator_default.phtml');

		$news = new News;
		$actual = $news->getAll(false, $pager);
		$msg = 'ActiveRecord::getAll() returns wrong result!';
		self::assertSame($expected, $actual, $msg);
	}

	public function getAllProvider(): array
	{
		return [
			[
				[
					[
						'id'      => '1',
						'title'   => "title_1",
						'content' => "content_1",
						'author'  => "author_1"
					],
					[
						'id'      => '2',
						'title'   => 'title_2',
						'content' => 'content_2',
						'author'  => 'author_2'
					],
					[
						'id'      => '3',
						'title'   => 'title_3',
						'content' => 'content_3',
						'author'  => 'author_3'
					]
				],
				[
					[
						'id'      => '1',
						'title'   => "title_1",
						'content' => "content_1",
						'author'  => "author_1"
					],
					[
						'id'      => '2',
						'title'   => 'title_2',
						'content' => 'content_2',
						'author'  => 'author_2'
					],
					[
						'id'      => '3',
						'title'   => 'title_3',
						'content' => 'content_3',
						'author'  => 'author_3'
					]
				],
			],
			[
				[],
				false,
			]
		];
	}


	public function testSave(): void
	{
		$adapter = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['query', 'escape', 'getLastInsertId'])
			->getMock();
		$adapter->expects(self::exactly(2))
			->method('query')
			->willReturn(true);
		$adapter->expects(self::once())
			->method('getLastInsertId')
			->willReturn(21);
		$adapter->expects(self::exactly(6))
			->method('escape')
			->willReturn('string');

		Db::setAdapter($adapter);

		$news = new News;
		$news->title = 'title_21';
		$news->content = 'content_21';
		$news->author = 'author_21';

		$expected = true;
		$result = $news->save();
		$msg = 'ActiveRecord::save() returns wrong result!';
		self::assertSame($expected, $result, $msg);

		$news->title = 'updated_title_21';

		$expected = true;
		$result = $news->save();
		$msg = 'ActiveRecord::save() returns wrong result!';
		self::assertSame($expected, $result, $msg);
	}

	public function testDelete(): void
	{
		$adapter = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['query'])
			->getMock();
		$adapter->expects(self::once())
			->method('query')
			->willReturn(true);

		Db::setAdapter($adapter);

		$news = new News;
		$news->id = 21;

		$expected = true;
		$result = $news->delete();
		$msg = 'ActiveRecord::delete() returns wrong result!';
		self::assertSame($expected, $result, $msg);
	}

	public function testDeleteException(): void
	{
		$this->expectException(Exception::class);
		$this->expectExceptionMessage('Not found model id!');

		(new News)->delete();
	}

	public function testSetProperties(): void
	{
		$news = new News;
		$actual = $news->setProperties([
			'id'      => 21,
			'title'   => 'title_21',
			'content' => 'content_21',
			'author'  => 'author_21'
		]);

		$expected = new News;
		$expected->id = 21;
		$expected->title = 'title_21';
		$expected->content = 'content_21';
		$expected->author = 'author_21';

		$msg = 'Wrong ActiveRecord::setProperties() behavior!';
		self::assertEquals($expected, $news, $msg);

		$expected = $news;
		$msg = 'ActiveRecord::setProperties() returns wrong result!';
		self::assertSame($expected, $actual, $msg);
	}

	public function testGetProperties(): void
	{
		$expected = [
			'id'      => '3',
			'title'   => 'title_3',
			'content' => 'content_3',
			'author'  => 'author_3'
		];

		$adapter = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['row'])
			->getMock();
		$adapter->expects(self::once())
			->method('row')
			->willReturn($expected);

		Db::setAdapter($adapter);

		$news = new News;
		$news->getById(3);
		$result = [
			'id'      => '',
			'title'   => '',
			'content' => '',
			'author'  => ''
		];
		$news->getProperties($result);
		$msg = 'ActiveRecord::getProperties() wrong behavior!';
		self::assertSame($expected, $result, $msg);
	}

	public function testToArray(): void
	{
		$expected = [
			'id'      => '3',
			'title'   => 'title_3',
			'content' => 'content_3',
			'author'  => 'author_3'
		];

		$news = new News;
		$news->id = '3';
		$news->title = 'title_3';
		$news->content = 'content_3';
		$news->author = 'author_3';

		$actual = $news->toArray();
		$msg = 'ActiveRecord::toArray() returns wrong result!';
		self::assertSame($expected, $actual, $msg);
	}

	/**
	 * @dataProvider findProvider
	 */
	public function testFind($id, $expected): void
	{
		$expected_news = new News;

		if ($expected) {
			$expected_news->id      = $id;
			$expected_news->title   = "title_$id";
			$expected_news->content = "content_$id";
			$expected_news->author  = "author_$id";
		}

		$db_result = $expected
			? [
				'id'      => $id,
				'title'   => "title_$id",
				'content' => "content_$id",
				'author'  => "author_$id"
			]
			: [];

		$adapter = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['row'])
			->getMock();
		$adapter->expects(self::once())
			->method('row')
			->willReturn($db_result);

		Db::setAdapter($adapter);

		$actual_news = new News;
		$filter = new DbFilter;
		$filter->setWhere("id = $id");
		$actual = $actual_news->find($filter);
		$msg = 'ActiveRecord::find() returns wrong result!';
		self::assertSame($expected, $actual, $msg);

		$msg = 'Wrong ActiveRecord::find() behavior!';
		self::assertEquals($expected_news, $actual_news, $msg);
	}

	public function findProvider(): array
	{
		return [
			[3, true],
			[200, false]
		];
	}

	/**
	 * @dataProvider queryProvider
	 */
	public function testQuery($pager, $expected, $found_rows): void
	{
		$adapter = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['rows', 'getFoundRows'])
			->getMock();
		$adapter->expects(self::once())
			->method('rows')
			->willReturn($expected);

		if ($found_rows) {
			$adapter->expects(self::once())
				->method('getFoundRows')
				->willReturn($found_rows);
		}

		Db::setAdapter($adapter);

		$sql = "SELECT * FROM user";

		$news = new News;
		$result = $news->query($sql, $pager);
		$msg = 'ActiveRecord::query() returns wrong result!';
		self::assertSame($expected, $result, $msg);
	}

	public function queryProvider(): array
	{
		$expected1 = [];

		for ($i = 1; $i < 21; $i++) {
			$expected1[] = [
				'id'      => "$i",
				'title'   => "title_$i",
				'content' => "content_$i",
				'author'  => "author_$i"
			];
		}

		$expected2 = [];

		for ($i = 1; $i < 6; $i++) {
			$expected2[] = [
				'id'      => "$i",
				'title'   => "title_$i",
				'content' => "content_$i",
				'author'  => "author_$i"
			];
		}

		$expected3 = [];

		for ($i = 11; $i < 16; $i++) {
			$expected3[] = [
				'id'      => "$i",
				'title'   => "title_$i",
				'content' => "content_$i",
				'author'  => "author_$i"
			];
		}

		return [
			[false, $expected1, 0],
			[new DbPaginator(''), $expected2, 5],
			[new DbPaginator('', 3), $expected3, 5],
			[false, false, 0]
		];
	}
}
