<?php
/**
 * Юнит-тест для класса Application
 * @file    Application.php
 *
 * PHP version 7.1+
 *
 * @author  Alexander Yancharuk <alex at itvault dot info>
 * @date    Втр Янв 22 22:53:39 2013
 * @license The BSD 3-Clause License
 *          <https://tldrlegal.com/license/bsd-3-clause-license-(revised)>.
 */

namespace Veles\Tests\Application;

use PHPUnit\Framework\TestCase;
use Veles\Application\Application;
use Veles\Request\HttpGetRequest;
use Veles\Routing\IniConfigLoader;
use Veles\Routing\Route;
use Veles\Routing\RoutesConfig;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-22 at 22:53:39.
 * @group application
 */
class ApplicationTest extends TestCase
{
	/**
	 * Unit-test for Application::run
	 *
	 * @covers       \Veles\Application\Application::run
	 * @dataProvider runProvider
	 *
	 * @param $url
	 * @param $parse_result
	 * @param $expected
	 */
	public function testRun($url, $parse_result, $expected)
	{
		$this->expectOutputString($expected['output']);

		/** @var \Veles\Routing\Route $route */
		$route = $this->getMockBuilder(Route::class)
			->setMethods(['parseUri'])
			->getMock();
		$route->method('parseUri')->willReturn($parse_result);

		$config = new RoutesConfig(
			new IniConfigLoader(TEST_DIR . '/Project/routes.ini')
		);
		$route->setConfigHandler($config)->init();

		$app = new Application;
		$app->setRoute($route)->run();

		$actual = $app->getRoute()->getParams();

		$msg = "Wrong Route::params in $url";
		$this->assertSame($expected['params'], $actual, $msg);
	}

	/**
	 * DataProvider for Application::run
	 */
	public function runProvider()
	{
		$uri = '/page/2';
		$parse_result = [$uri, 'page'];
		$expected = [
			'params' => ['page' => '2'],
			'output' => <<<EOF
<!DOCTYPE html>
<html>
<head>
	<title>Veles is a fast PHP framework</title>
</head>
<body>
	<div id="main_wrapper">
		Test complete!
	</div>
	<div id="footer_wrapper">
		Hello World!
	</div>
</body>
</html>

EOF
		];

		return [[$uri, $parse_result, $expected]];
	}

	/**
	 * @covers \Veles\Application\Application::setRoute
	 */
	public function testSetRoute()
	{
		$expected = (new Route)->setConfigHandler(
			new RoutesConfig(new IniConfigLoader(TEST_DIR . '/Project/routes.ini'))
		);

		$object = (new Application)->setRoute($expected);

		$msg = 'Application::setRoute() wrong behavior!';
		$this->assertAttributeSame($expected, 'route', $object, $msg);
	}

	/**
	 * @covers \Veles\Application\Application::getRoute
	 */
	public function testGetRoute()
	{
		$expected = (new Route)->setConfigHandler(
			new RoutesConfig(new IniConfigLoader(TEST_DIR . '/Project/routes.ini'))
		);

		$object = (new Application)->setRoute($expected);

		$actual = $object->getRoute();

		$msg = 'Application::getRoute() returns wrong result!';
		$this->assertSame($expected, $actual, $msg);
	}

	/**
	 * @covers \Veles\Application\Application::setRequest
	 */
	public function testSetRequest()
	{
		$expected = new HttpGetRequest;

		$object = (new Application)->setRequest($expected);

		$msg = 'Application::setRequest() wrong behavior!';
		$this->assertAttributeSame($expected, 'request', $object, $msg);
	}

	/**
	 * @covers \Veles\Application\Application::getRequest
	 */
	public function testGetRequest()
	{
		$expected = new HttpGetRequest;

		$object = (new Application)->setRequest($expected);

		$actual = $object->getRequest();

		$msg = 'Application::getRequest() returns wrong result!';
		$this->assertSame($expected, $actual, $msg);
	}
}
