<?php
/**
 * Юнит-тест для класса Application
 * @file    Application.php
 *
 * PHP version 5.6+
 *
 * @author  Alexander Yancharuk <alex at itvault dot info>
 * @date    Втр Янв 22 22:53:39 2013
 * @license The BSD 3-Clause License
 *          <https://tldrlegal.com/license/bsd-3-clause-license-(revised)>.
 */

namespace Veles\Tests\Application;

use PHPUnit_Framework_TestCase;
use Veles\Application\Application;
use Veles\Application\Environment;
use Veles\Routing\IniConfigLoader;
use Veles\Routing\Route;
use Veles\Routing\RoutesConfig;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-22 at 22:53:39.
 * @group application
 */
class ApplicationTest extends PHPUnit_Framework_TestCase
{
	/**
	 * Unit-test for Application::run
	 * @covers       \Veles\Application\Application::run
	 * @dataProvider runProvider
	 *
	 * @param $url
	 * @param $expected
	 */
	public function testRun($url, $expected)
	{
		$this->expectOutputString($expected['output']);

		/** @var \Veles\Routing\Route $route */
		$route = $this->getMockBuilder('\Veles\Routing\Route')
			->setMethods(['getUri'])
			->getMock();
		$route->method('getUri')->willReturn($url);

		$config = new RoutesConfig(
			new IniConfigLoader(TEST_DIR . '/Project/routes.ini')
		);
		$route->setConfigHandler($config)->init();

		$app = new Application;
		$app->setRoute($route)->run();

		$result = $app->getRoute()->getParams();

		$msg = "Wrong Route::params in $url";
		$this->assertSame($expected['params'], $result, $msg);
	}

	/**
	 * DataProvider for Application::run
	 */
	public function runProvider()
	{
		$uri      = '/page-2.html';
		$expected = [
			'params'    => ['page' => '2'],
			'output' => <<<EOF
<!DOCTYPE html>
<html>
<head>
	<title>Veles is a fast PHP framework</title>
</head>
<body>
	<div id="main_wrapper">
		Test complete!
	</div>
	<div id="footer_wrapper">
		Hello World!
	</div>
</body>
</html>

EOF
		];

		return [[$uri, $expected]];
	}

	/**
	 * @covers \Veles\Application\Application::setRoute
	 */
	public function testSetRoute()
	{
		$expected = (new Route)->setConfigHandler(
			new RoutesConfig(new IniConfigLoader(TEST_DIR . '/Project/routes.ini'))
		);

		$object = (new Application)->setRoute($expected);

		$msg = 'Application::setRoute() wrong behavior!';
		$this->assertAttributeSame($expected, 'route', $object, $msg);
	}

	/**
	 * @covers \Veles\Application\Application::getRoute
	 */
	public function testGetRoute()
	{
		$expected = (new Route)->setConfigHandler(
			new RoutesConfig(new IniConfigLoader(TEST_DIR . '/Project/routes.ini'))
		);

		$object = (new Application)->setRoute($expected);

		$actual = $object->getRoute();

		$msg = 'Application::getRoute() returns wrong result!';
		$this->assertSame($expected, $actual, $msg);
	}

	/**
	 * @covers       \Veles\Application\Application::setVersion
	 */
	public function testSetVersion()
	{
		$expected = '0.0.234';
		$object = (new Application)->setVersion($expected);

		$msg = 'IdbApiApplication::setVersion() wrong behavior!';
		$this->assertAttributeSame($expected, 'version', $object, $msg);
	}

	/**
	 * @covers       \Veles\Application\Application::getVersion
	 */
	public function testGetVersion()
	{
		$expected = '0.0.234';
		$object = (new Application)->setVersion($expected);

		$actual = $object->getVersion();

		$msg = 'IdbApiApplication::getVersion() returns wrong result!';
		$this->assertSame($expected, $actual, $msg);
	}

	/**
	 * @covers \Veles\Application\Application::setEnvironment
	 */
	public function testSetEnvironment()
	{
		$expected = (new Environment)
			->setName('development')
			->setStaticPath('https://static.project.com');

		$object = (new Application)->setEnvironment($expected);

		$msg = 'Application::setEnvironment() wrong behavior!';
		$this->assertAttributeSame($expected, 'environment', $object, $msg);
	}

	/**
	 * @covers \Veles\Application\Application::getEnvironment
	 */
	public function testGetEnvironment()
	{
		$expected = (new Environment)
			->setName('development')
			->setStaticPath('https://static.project.com');

		$object = (new Application)->setEnvironment($expected);

		$actual = $object->getEnvironment();

		$msg = 'Application::getEnvironment() returns wrong result!';
		$this->assertSame($expected, $actual, $msg);
	}
}
