<?php
namespace Tests\Request;

use PHPUnit\Framework\TestCase;
use Veles\Request\HttpJsonSchemaRequest;
use Veles\Request\Validator\Validator;
use Veles\Exceptions\Http\UnprocessableException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-01-18 at 12:31:15.
 * @group request
 */
class HttpJsonSchemaRequestTest extends TestCase
{
	/**
	 * @var HttpJsonSchemaRequest
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp(): void
	{
		$this->object = new HttpJsonSchemaRequest;
	}

	public function testGetBody(): void
	{
		$filename = uniqid() . '.txt';
		$json = '{"message": "this is text"}';
		$expected = new \stdClass;
		$expected->message = 'this is text';
		file_put_contents($filename, $json);
		$this->object->setStream($filename);

		$result = $this->object->getBody();
		unlink($filename);

		$msg = 'HttpJsonSchemaRequest::getBody() returns wrong result!';
		self::assertEquals($expected, $result, $msg);
	}

	public function testCheck(): void
	{
		$definitions = '
		{
		  "$schema": "http://json-schema.org/draft-04/schema#",
		  "type": "object",
		  "properties": {
			"message": {
			  "type": "string"
			}
		  },
		  "required": ["message"]
		}';
		$json = '{"message": "this is tests string"}';
		$expected = ['message' => "this is tests string"];

		$this->object = $this->getMockBuilder(HttpJsonSchemaRequest::class)
			->onlyMethods(['getBody'])
			->getMock();

		$this->object->expects(self::once())
			->method('getBody')
			->willReturn(json_decode($json));

		$validator = $this->getMockBuilder(Validator::class)
			->onlyMethods(['check', 'isValid'])
			->getMock();

		$validator->expects(self::once())
			->method('check')
			->with(json_decode($json), json_decode($definitions));

		$validator->expects(self::once())
			->method('isValid')
			->willReturn(true);

		$this->object->setValidator($validator);

		$this->object->check($definitions);
	}

	public function testCheckException(): void
	{
		$this->expectException(UnprocessableException::class);

		$definitions = '
		{
		  "$schema": "http://json-schema.org/draft-04/schema#",
		  "type": "object",
		  "properties": {
			"message": {
			  "type": "string"
			}
		  },
		  "required": ["message"]
		}';

		$errors = ['ERROR_MSG'];
		$json   = '{"message": "this is tests string"}';

		$this->object = $this->getMockBuilder(HttpJsonSchemaRequest::class)
			->onlyMethods(['getBody'])
			->getMock();

		$this->object->expects(self::once())
			->method('getBody')
			->willReturn(json_decode($json));

		$validator = $this->getMockBuilder(Validator::class)
			->onlyMethods(['check', 'isValid', 'getErrors'])
			->getMock();

		$validator->expects(self::once())
			->method('check')
			->with(json_decode($json), json_decode($definitions));

		$validator->expects(self::once())
			->method('isValid')
			->willReturn(false);

		$validator->expects(self::once())
			->method('getErrors')
			->willReturn($errors);

		$this->object->setValidator($validator);
		$this->expectOutputString('{"errors":["ERROR_MSG"]}');

		$this->object->check($definitions);
	}
}
