<?php
namespace Tests\Request;

use Veles\Request\HttpPostRequest;
use Veles\Request\Validator\Validator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-01-18 at 11:11:17.
 * @group request
 */
class HttpPostRequestTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var HttpPostRequest
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new HttpPostRequest;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		unset($_POST);
	}

	/**
	 * @covers       \Veles\Request\HttpPostRequest::getBody
	 *
	 * @dataProvider postProvider
	 *
	 * @param $expected
	 */
	public function testGetBody($expected)
	{
		$_POST = $expected;

		$actual = $this->object->getBody();
		$msg = 'HttpPostRequest returns wrong result!';
		$this->assertSame($expected, $actual, $msg);
	}

	public function postProvider()
	{
		return [
			[[uniqid(), uniqid()]],
			[[uniqid()]],
			[[uniqid()]]
		];
	}

	/**
	 * @covers       \Veles\Request\HttpPostRequest::check
	 * @covers       \Veles\Request\HttpRequestAbstract::setData
	 *
	 * @param $post
	 * @param $definitions
	 * @param $validator
	 *
	 * @dataProvider checkProvider
	 */
	public function testCheck($post, $definitions, $validator)
	{
		$_POST = $post;

		$this->object->setValidator($validator);

		$this->object->check($definitions);
		$msg = 'HttpPostRequest wrong behavior!';
		$this->assertAttributeSame($post, 'data', $this->object, $msg);
	}

	public function checkProvider()
	{
		$post1 = [uniqid()];
		$definitions1 = uniqid();

		$validator1 = $this->getMockBuilder(Validator::class)
			->setMethods(['check', 'isValid'])
			->getMock();

		$validator1->expects($this->once())
			->method('check')
			->with($post1, $definitions1);

		$validator1->expects($this->once())
			->method('isValid')
			->willReturn(true);

		$post2 = [uniqid()];
		$definitions2 = uniqid();

		$validator2 = $this->getMockBuilder(Validator::class)
			->setMethods(['check', 'isValid'])
			->getMock();

		$validator2->expects($this->once())
			->method('check')
			->with($post2, $definitions2);

		$validator2->expects($this->once())
			->method('isValid')
			->willReturn(true);

		return [
			[
				$post1, $definitions1, $validator1
			],
			[
				$post2, $definitions2, $validator2
			]
		];
	}

	/**
	 * @covers                   \Veles\Request\HttpPostRequest::check
	 *
	 * @param $post
	 * @param $definitions
	 * @param $validator
	 *
	 * @dataProvider             checkExceptionProvider
	 * @expectedException \Veles\Exceptions\Http\UnprocessableException
	 */
	public function testCheckException($post, $definitions, $validator)
	{
		$_POST = $post;

		$this->object->setValidator($validator);
		$this->expectOutputString('{"errors":["ERROR_MSG"]}');

		$this->object->check($definitions);
		$msg = 'HttpPostRequest wrong behavior!';
		$this->assertAttributeSame($post, 'data', $this->object, $msg);
	}

	public function checkExceptionProvider()
	{
		$post1 = [uniqid()];
		$definitions1 = uniqid();
		$error = ['ERROR_MSG'];

		$validator1 = $this->getMockBuilder(Validator::class)
			->setMethods(['check', 'isValid', 'getErrors'])
			->getMock();

		$validator1->expects($this->once())
			->method('check')
			->with($post1, $definitions1);

		$validator1->expects($this->once())
			->method('isValid')
			->willReturn(false);

		$validator1->expects($this->once())
			->method('getErrors')
			->willReturn($error);

		return [
			[
				$post1, $definitions1, $validator1
			]
		];
	}
}
