<?php
namespace Tests\Request;

use PHPUnit\Framework\TestCase;
use Veles\Request\HttpPostRequest;
use Veles\Request\HttpRequestAbstract;
use Veles\Request\Validator\Adapters\JsonSchemaAdapter;
use Veles\Request\Validator\Validator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-01-18 at 12:03:02.
 * @group request
 */
class HttpRequestAbstractTest extends TestCase
{
	/**
	 * @var HttpRequestAbstract
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp(): void
	{
		$this->object = new HttpPostRequest;
	}

	public function testGetValidator(): void
	{
		$expected = new Validator;

		$this->object->setValidator($expected);
		$actual = $this->object->getValidator();

		$msg = 'HttpRequestAbstract::getValidator() returns wrong result!';
		self::assertSame($expected, $actual, $msg);
	}

	public function testGetData(): void
	{
		$expected = [uniqid()];
		$definitions = uniqid();

		$_POST = $expected;

		$validator = $this->getMockBuilder(Validator::class)
			->onlyMethods(['isValid', 'getData'])
			->getMock();

		$validator->expects(self::once())
			->method('isValid')
			->willReturn(true);

		$validator->expects(self::once())
			->method('getData')
			->willReturn($expected);

		$adapter = $this->getMockBuilder(JsonSchemaAdapter::class)
			->onlyMethods(['check'])
			->disableOriginalConstructor()
			->getMock();

		$adapter->expects(self::once())
			->method('check');

		$validator->setAdapter($adapter);

		$this->object->setValidator($validator);

		$actual = $this->object->getData($definitions);
		$msg = 'HttpRequestAbstract::getData returns wrong result!';
		self::assertSame($expected, $actual, $msg);
	}
}
