<?php
namespace Tests\Request;

use PHPUnit\Framework\TestCase;
use Veles\Request\RequestFactory;
use Veles\Request\HttpJsonRequest;
use Veles\Request\HttpPostRequest;
use Veles\Request\HttpGetRequest;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-23 at 17:41:07.
 * @group request
 */
class RequestFactoryTest extends TestCase
{
	/**
	 * @var RequestFactory
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp(): void
	{
		$this->object = new RequestFactory;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers \Veles\Request\RequestFactory::create
	 *
	 * @param $content_type
	 * @param $expected
	 *
	 * @dataProvider createProvider
	 */
	public function testCreate($content_type, $expected)
	{
		$actual = $this->object->create($content_type);
		$msg = 'RequestFactory::create() returns wrong result!';
		$this->assertInstanceOf($expected, $actual, $msg);
	}

	public function createProvider()
	{
		return [
			[null, HttpGetRequest::class],
			['', HttpGetRequest::class],
			['text/html', HttpGetRequest::class],
			['text/html; charset=UTF-8', HttpGetRequest::class],
			['application/x-www-form-urlencoded; charset=UTF-8', HttpPostRequest::class],
			['application/x-www-form-urlencoded', HttpPostRequest::class],
			['multipart/form-data', HttpPostRequest::class],
			['multipart/form-data; charset=UTF-8', HttpPostRequest::class],
			['application/json', HttpJsonRequest::class]
		];
	}
}
