<?php
/**
 * Unit-test for AutoLoader class
 *
 * @file      AutoLoaderTest.php
 *
 * PHP version 7.1+
 *
 * @author    Alexander Yancharuk <alex at itvault dot info>
 * @copyright © 2012-2020 Alexander Yancharuk
 * @date      Вск Янв 20 22:07:49 2013
 * @license   The BSD 3-Clause License
 *            <https://tldrlegal.com/license/bsd-3-clause-license-(revised)>.
 */

namespace Veles\Tests;

use PHPUnit\Framework\TestCase;
use Veles\AutoLoader;
use Veles\Tests\AutoLoaderFake;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-20 at 21:31:21.
 * @group RootClasses
 */
class AutoLoaderTest extends TestCase
{
	/**
	 * @group RootClasses
	 */
	public function testInit(): void
	{
		// Удаляем автолоадер из списка зарегистрированных
		spl_autoload_unregister('Veles\AutoLoader::load');

		AutoLoader::init();

		$auto_loaders = spl_autoload_functions();
		$actual = array_search([AutoLoader::class, 'load'], $auto_loaders, true);

		$msg = 'AutoLoader function not registered!';
		self::assertNotFalse($actual, $msg);
	}

	/**
	 * @group RootClasses
	 */
	public function testLoad(): void
	{
		AutoLoader::load(AutoLoaderFake::class);

		$actual = array_search(AutoLoaderFake::class, get_declared_classes());

		$msg = 'Class AutoLoaderFake did not loaded';
		self::assertNotFalse($actual, $msg);
	}
}
