<?php
/**
 * Юнит-тест для класса Password
 * @file    PasswordTest.php
 *
 * PHP version 7.1+
 *
 * @author  Alexander Yancharuk <alex at itvault dot info>
 * @date    Вск Янв 20 15:58:07 2013
 * @license The BSD 3-Clause License
 *          <https://tldrlegal.com/license/bsd-3-clause-license-(revised)>.
 */

namespace Veles\Tests\Auth;

use PHPUnit\Framework\TestCase;
use Veles\Auth\Password;
use Veles\Helper;
use Veles\Model\User;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-22 at 08:31:29.
 * @group auth
 */
class PasswordTest extends TestCase
{
	/**
	 * @dataProvider checkCookieHashProvider
	 */
	public function testCheckCookieHash($user, $cookie_hash, $expected): void
	{
		$result = Password::checkCookieHash($user, $cookie_hash);

		$txt_result = $result ? 'true' : 'false';
		$msg = "CheckCookieHash \"$cookie_hash\" has wrong result: $txt_result";
		self::assertSame($expected, $result, $msg);
	}

	public function checkCookieHashProvider(): array
	{
		$user = new User;
		$user->hash = crypt('password', '$2a$07$' . Helper::genStr() . '$');

		return [
			[$user, $user->getCookieHash(), true],
			[$user, 'wrongHash', false]
		];
	}

	/**
	 * @dataProvider checkProvider
	 */
	public function testCheck($user, $password, $expected): void
	{
		$actual = Password::check($user, $password);

		$txt_result = $actual ? 'true' : 'false';
		$msg = "Password::check \"$password\" has wrong result: $txt_result";
		self::assertSame($expected, $actual, $msg);
	}

	public function checkProvider(): array
	{
		$user = new User;
		$user->hash = crypt('password', '$2y$07$' . Helper::genStr());

		return [
			[$user, 'password', true],
			[$user, 'wrongPassword', false]
		];
	}
}
