<?php
namespace Veles\Tests\Auth;

use PHPUnit\Framework\TestCase;
use Veles\Auth\UsrGroup;
use Veles\Auth\UsrAuth;
use Veles\Model\User;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-24 at 16:37:03.
 * @group auth
 */
class UsrAuthTest extends TestCase
{
	/**
	 * @var UsrAuth
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp(): void
	{
		$this->object = UsrAuth::instance();
	}

	public function testInstance(): void
	{
		UsrAuthCleaner::unsetInstance();

		$expected = UsrAuth::class;
		$result = $this->object::instance();
		$msg = 'UsrAuth::instance() return wrong result!';
		self::assertInstanceOf($expected, $result, $msg);
	}

	public function testGetErrors(): void
	{
		$expected = 0;
		$result = $this->object::getErrors();
		$msg = 'UsrAuth::getErrors returns wrong result!';
		self::assertSame($expected, $result, $msg);
	}

	/**
	 * @dataProvider hasAccessProvider
	 */
	public function testHasAccess($group, $expected): void
	{
		$result = $this->object::hasAccess($group);
		$msg    = 'UsrAuth::hasAccess() returns wrong result!';
		self::assertSame($expected, $result, $msg);
	}

	public function hasAccessProvider(): array
	{
		return [
			[UsrGroup::ADMIN, false],
			[UsrGroup::ADMIN + UsrGroup::MANAGER, false],
			[UsrGroup::DELETED + UsrGroup::MANAGER, false],
			[UsrGroup::GUEST + UsrGroup::DELETED, false],
			[UsrGroup::GUEST, true],
			[UsrGroup::MANAGER, false],
			[UsrGroup::MODERATOR, false],
			[UsrGroup::REGISTERED, false]
		];
	}

	public function testGetUser(): void
	{
		$expected = User::class;
		$result = $this->object::getUser();
		$msg = 'UsrAuth::getUser() returns wrong result!';
		self::assertInstanceOf($expected, $result, $msg);
	}
}
