<?php
namespace Veles\Tests\Auth\Strategies;

use PHPUnit\Framework\TestCase;
use Veles\Auth\Strategies\LoginFormStrategy;
use Veles\DataBase\Adapters\PdoAdapter;
use Veles\DataBase\Db;
use Veles\Model\User;
use Veles\Tests\DataBase\DbCopy;

require_once 'setcookie_stub.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-25 at 23:09:50.
 * @group auth
 */
class LoginFormStrategyTest extends TestCase
{
	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown(): void
	{
		DbCopy::unsetAdapter();
	}

	/**
	 * @dataProvider identifyProvider
	 *
	 * @param $mail
	 * @param $pass
	 * @param $db_result
	 * @param $expected
	 * @param $expected_errors
	 */
	public function testIdentify($mail, $pass, $db_result, $expected, $expected_errors): void
	{
		$adapter = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['row'])
			->getMock();
		$adapter->expects(self::once())
			->method('row')
			->willReturn($db_result);

		Db::setAdapter($adapter);

		$object = new LoginFormStrategy($mail, $pass, new User);
		$actual = $object->identify();

		$msg = 'LoginFormStrategy::identify() returns wrong result!';
		self::assertSame($expected, $actual, $msg);

		$actual = $object->getErrors();
		$msg = 'LoginFormStrategy::getErrors() returns wrong result!';
		self::assertSame($expected_errors, $actual, $msg);
	}

	public function identifyProvider(): array
	{
		$true_result = [
			'id'         => 1,
			'email'      => 'mail@mail.org',
			'hash'       => '$2a$07$usesomesillystringforeGlOaUExBSD9HxuEYk2ZFaeDhggU716O',
			'group'      => 'user',
			'last_login' => '1980-12-12'
		];

		$false_result = false;

		return [
			['mail@mail.org', 'superpass', $true_result, true, 0],
			['mail@mail.org', 'bad_pass', $true_result, false, 2],
			['mail500@mail.org', 'asf1900', $false_result, false, 1],
			['mail@maild.org', 'superpasslakj()', $false_result, false, 1],
			['mail@mails.org', 'usell', $false_result, false, 1]
		];
	}

	public function testGetLogin(): void
	{
		$expected = 'info@mail.ru';
		$pass = uniqid();

		$object = new LoginFormStrategy($expected, $pass, new User);
		$result = $object->getLogin();

		$msg = 'LoginFormStrategy::getLogin() wrong behavior!';
		self::assertSame($expected, $result, $msg);
	}

	public function testGetPassword(): void
	{
		$login = 'info@mail.ru';
		$expected = uniqid();

		$object = new LoginFormStrategy($login, $expected, new User);
		$result = $object->getPassword();

		$msg = 'LoginFormStrategy::getPassword() wrong behavior!';
		self::assertSame($expected, $result, $msg);
	}
}
