<?php

namespace Veles\Tests\ErrorHandler;

use PHPUnit\Framework\TestCase;
use Veles\ErrorHandler\FatalErrorHandler;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-11 at 20:07:35.
 *
 * @group ErrorHandler
 */
class FatalErrorHandlerTest extends TestCase
{
	/**
	 * @var FatalErrorHandler
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp(): void
	{
		$this->object = new FatalErrorHandler;
	}

	public function testRun(): void
	{
		$expected = null;
		$this->object->run();
		$actual = $this->object->getVars();

		$msg = 'FatalErrorHandler::run() wrong behavior!';
		self::assertSame($expected, $actual, $msg);

		/** @noinspection PhpUndefinedVariableInspection */
		@$b = $a['none'];

		$time = strftime('%Y-%m-%d %H:%M:%S', time());

		$message = (PHP_VERSION_ID < 70400)
			? 'Undefined variable: a'
			: 'Trying to access array offset on value of type null';

		$expected = [
			'type'    => 8,
			'message' => $message,
			'file'    => realpath(__FILE__),
			'line'    => 39,
			'time'    => $time,
			'stack'   => [],
			'defined' => [],
		];

		$this->object->setTime($time);
		$this->object->run();
		$actual = $this->object->getVars();

		$msg = 'FatalErrorHandler::run() wrong behavior!';
		self::assertSame($expected, $actual, $msg);
	}
}
