<?php
namespace Tests\Controllers;

use Veles\Application\Application;
use Veles\Controllers\BaseController;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-24 at 10:20:22.
 * @group controllers
 */
class BaseControllerTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var BaseController
	 */
	protected $object;
	protected $application;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->application = new Application;
		$this->object = new BaseController($this->application);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Veles\Controllers\BaseController::getApplication
	 */
	public function testGetApplication()
	{
		$expected = $this->application;
		$actual   = $this->object->getApplication();

		$msg = 'BaseController::getApplication() returns wrong result!';
		$this->assertSame($expected, $actual, $msg);
	}

	/**
	 * @covers Veles\Controllers\BaseController::setApplication
	 */
	public function testSetApplication()
	{
		$expected = (new Application)->setVersion('0.0.234');
		$this->object->setApplication($expected);

		$msg = 'BaseController::setApplication() wrong behavior!';
		$this->assertAttributeSame($expected, 'application', $this->object, $msg);
	}
}
