<?php
namespace Tests\Controllers;

use PHPUnit\Framework\TestCase;
use Veles\Application\Application;
use Veles\Controllers\RestApiController;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-12-08 at 10:42:40.
 * @group controllers
 */
class RestApiControllerTest extends TestCase
{
	/**
	 * @var RestApiController
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp(): void
	{
		$this->object = new RestApiController(new Application);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown(): void
	{
		unset($_SERVER['REQUEST_METHOD']);
	}

	/**
	 * @covers       \Veles\Controllers\RestApiController::index
	 * @dataProvider indexExceptionProvider
	 *
	 * @param $method
	 *
	 * @throws \Veles\Exceptions\Http\NotAllowedException
	 * @expectedException \Veles\Exceptions\Http\NotAllowedException
	 */
	public function testIndexException($method)
	{
		$_SERVER['REQUEST_METHOD'] = $method;
		$this->object->index();
	}

	public function indexExceptionProvider()
	{
		return [
			['HEAD'],
			['TRACE']
		];
	}

	/**
	 * @covers       \Veles\Controllers\RestApiController::index
	 *
	 * @dataProvider indexProvider
	 *
	 * @param $method
	 */
	public function testIndex($method)
	{
		$_SERVER['REQUEST_METHOD'] = $method;
		$object = new RestApiExampleController(new Application);

		$expected = [];
		$actual = $object->index();

		$msg = 'RestApiController::index() returns wrong result!';
		$this->assertSame($expected, $actual, $msg);
	}

	public function indexProvider()
	{
		return [
			['GET'],
			['POST'],
			['PUT'],
			['DELETE']
		];
	}

	/**
	 * @covers \Veles\Controllers\RestApiController::__call()
	 * @expectedException \Veles\Exceptions\Http\NotAllowedException
	 */
	public function testPost()
	{
		$_SERVER['REQUEST_METHOD'] = 'POST';
		$this->object->index();
	}

	/**
	 * @covers \Veles\Controllers\RestApiController::__call()
	 * @expectedException \Veles\Exceptions\Http\NotAllowedException
	 */
	public function testGet()
	{
		$_SERVER['REQUEST_METHOD'] = 'GET';
		$this->object->index();
	}

	/**
	 * @covers \Veles\Controllers\RestApiController::__call()
	 * @expectedException \Veles\Exceptions\Http\NotAllowedException
	 */
	public function testPut()
	{
		$_SERVER['REQUEST_METHOD'] = 'PUT';
		$this->object->index();
	}

	/**
	 * @covers \Veles\Controllers\RestApiController::__call()
	 *
	 * @expectedException \Veles\Exceptions\Http\NotAllowedException
	 */
	public function testDelete()
	{
		$_SERVER['REQUEST_METHOD'] = 'DELETE';
		$this->object->index();
	}
}
