<?php
namespace Veles\Tests\Routing\Exceptions;

use PHPUnit\Framework\TestCase;
use Veles\Routing\Exceptions\NotFoundException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-12 at 09:05:52.
 * @group route
 */
class NotFoundExceptionTest extends TestCase
{
	/**
	 * @var NotFoundException
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp(): void
	{
		$this->object = new NotFoundException;
	}

	public function testConstruct(): void
	{
		$actual = $this->object->getCode();
		$msg = 'NotFoundException::__construct() wrong behavior!';
		self::assertSame(0, $actual, $msg);
	}
}
