<?php
namespace Veles\Tests\CurlRequest;

use PHPUnit\Framework\TestCase;
use Veles\CurlRequest\CurlRequest;

require_once 'curl_errno.php';
require_once 'curl_error.php';
require_once 'curl_getinfo.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-23 at 10:43:20.
 *
 * @group curl-request
 */
class CurlAbstractTest extends TestCase
{
	/**
	 * @var CurlRequest
	 */
	protected $object;
	/** @var string  */
	protected $url = 'http://localhost';

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp(): void
	{
		$this->object = new CurlRequest($this->url);
	}

	public function testGetErrorCode(): void
	{
		$expected = 555;

		$actual = $this->object->getErrorCode();
		$msg = 'CurlAbstract::getErrorCode() returns wrong result!';
		self::assertSame($expected, $actual, $msg);
	}

	public function testGetError(): void
	{
		$expected = 'This is test error message!';

		$actual = $this->object->getError();
		$msg = 'CurlAbstract::getError() returns wrong result!';
		self::assertSame($expected, $actual, $msg);
	}

	/**
	 * @dataProvider getInfoProvider
	 */
	public function testGetInfo($expected, $option): void
	{
		$actual = $this->object->getInfo($option);
		$msg = 'CurlAbstract::getInfo() returns wrong result!';
		self::assertSame($expected, $actual, $msg);
	}

	public function getInfoProvider(): array
	{
		$option1 = null;
		$option2 = 'TEST_OPTION';

		return [
			['This is test info message!', $option1],
			["This is test info message for option: $option2!", $option2]
		];
	}

	public function testGetResource(): void
	{
		$actual = $this->object->getResource();
		$msg = 'CurlAbstract::getResource() returns wrong result!';
		self::assertSame('resource', gettype($actual), $msg);
	}
}
