<?php
namespace Veles\Tests\CurlRequest;

use PHPUnit\Framework\TestCase;
use Veles\CurlRequest\PostCurlRequest;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-23 at 13:50:58.
 *
 * @group curl-request
 */
class PostCurlRequestTest extends TestCase
{
	/**
	 * @var PostCurlRequest
	 */
	protected $object;
	/** @var string  */
	protected $url = 'http://localhost';

	protected function setUp(): void
	{
		$this->object = new PostCurlRequest($this->url);
	}

	/**
	 * @dataProvider setDataProvider
	 */
	public function testSetData($data): void
	{
		$actual = $this->object->setData($data);

		$msg = 'CurlRequest::setData() returns wrong result!';
		self::assertSame($this->object, $actual, $msg);
	}

	public function setDataProvider(): array
	{
		return [
			[
				['login' => 'boss', 'pass' => 'super']
			],
			[
				'login_boss'
			]
		];
	}
}
