<?php
namespace Veles\Tests\CurlRequest;

use Veles\CurlRequest\PostCurlRequest;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-23 at 13:50:58.
 *
 * @group curl-request
 */
class PostCurlRequestTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var PostCurlRequest
	 */
	protected $object;
	/** @var string  */
	protected $url = 'http://localhost';

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new PostCurlRequest($this->url);
	}

	/**
	 * @covers \Veles\CurlRequest\PostCurlRequest::setData
	 *
	 * @dataProvider setDataProvider
	 *
	 * @param $data
	 * @param $expected
	 */
	public function testSetData($expected, $data)
	{
		$actual = $this->object->setData($data);

		$msg = 'CurlRequest::setData() wrong behavior!';
		$this->assertAttributeSame($expected, 'options', $this->object, $msg);

		$msg = 'CurlRequest::setData() returns wrong result!';
		$this->assertSame($this->object, $actual, $msg);
	}

	public function setDataProvider()
	{
		return [
			[
				[
					CURLOPT_URL            => 'http://localhost',
					CURLOPT_RETURNTRANSFER => true,
					CURLOPT_CONNECTTIMEOUT => 10,
					CURLOPT_TIMEOUT        => 10,
					CURLOPT_POST           => true,
					CURLOPT_POSTFIELDS     => ['login' => 'boss', 'pass' => 'super']
				],
				['login' => 'boss', 'pass' => 'super']
			],
			[
				[
					CURLOPT_URL            => 'http://localhost',
					CURLOPT_RETURNTRANSFER => true,
					CURLOPT_CONNECTTIMEOUT => 10,
					CURLOPT_TIMEOUT        => 10,
					CURLOPT_POST           => true,
					CURLOPT_POSTFIELDS     => 'loginboss'
				],
				'loginboss'
			]
		];
	}
}
