<?php
namespace Veles\Tests\DataBase;

use Exception;
use PHPUnit\Framework\TestCase;
use Veles\DataBase\Adapters\PdoAdapter;
use Veles\DataBase\Db;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-11 at 15:34:36.
 * @group db
 */
class DbTest extends TestCase
{
	/**
	 * @var PdoAdapter
	 */
	protected $adapter;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp(): void
	{
		$this->adapter = new PdoAdapter;
	}

	protected function tearDown(): void
	{
		DbCopy::unsetAdapter();
	}

	public function testGetAdapter(): void
	{
		Db::setAdapter($this->adapter);

		$actual = Db::getAdapter();

		$msg = 'Db::getAdapter() returns wrong result!';
		self::assertSame($actual, $this->adapter, $msg);
	}

	public function testGetAdapterException(): void
	{
		$this->expectExceptionMessage(Exception::class);
		$this->expectExceptionMessage('Adapter not set!');

		Db::getAdapter();
	}

	public function testConnection(): void
	{
		$expected = 'connection name';

		$adapter = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['setConnection'])
			->getMock();
		$adapter->expects(self::once())
			->method('setConnection')
			->with($expected)
			->willReturn($adapter);

		Db::setAdapter($adapter);
		Db::connection($expected);
	}

	/**
	 * @dataProvider valueProvider
	 */
	public function testValue($adapter, $sql, $params, $types): void
	{
		Db::setAdapter($adapter);

		if ($types)
			Db::value($sql, $params, $types);
		elseif ($params)
			Db::value($sql, $params);
		else
			Db::value($sql);
	}

	public function valueProvider(): array
	{
		$sql1    = 'SELECT * FROM table_one';
		$params1 = [1, 1];
		$types1  = 'is';

		$adapter1 = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['value'])
			->getMock();
		$adapter1->expects(self::once())
			->method('value')
			->with($sql1, $params1, $types1)
			->willReturn($adapter1);

		$sql2    = 'SELECT * FROM table_two';
		$params2 = [1, 2];
		$types2  = null;

		$adapter2 = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['value'])
			->getMock();
		$adapter2->expects(self::once())
			->method('value')
			->with($sql2, $params2, $types2)
			->willReturn($adapter2);

		$sql3    = 'SELECT * FROM table_three';
		$params3 = [];
		$types3  = null;

		$adapter3 = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['value'])
			->getMock();
		$adapter3->expects(self::once())
			->method('value')
			->with($sql3, $params3, $types3)
			->willReturn($adapter3);

		return [
			[$adapter1, $sql1, $params1, $types1],
			[$adapter2, $sql2, $params2, $types2],
			[$adapter3, $sql3, $params3, $types3],
		];
	}

	/**
	 * @dataProvider rowProvider
	 */
	public function testRow($adapter, $sql, $params, $types): void
	{
		Db::setAdapter($adapter);

		if ($types)
			Db::row($sql, $params, $types);
		elseif ($params)
			Db::row($sql, $params);
		else
			Db::row($sql);
	}

	public function rowProvider(): array
	{
		$sql1    = 'SELECT * FROM table_one';
		$params1 = [1, 1];
		$types1  = 'is';

		$adapter1 = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['row'])
			->getMock();
		$adapter1->expects(self::once())
			->method('row')
			->with($sql1, $params1, $types1)
			->willReturn($adapter1);

		$sql2    = 'SELECT * FROM table_two';
		$params2 = [1, 2];
		$types2  = null;

		$adapter2 = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['row'])
			->getMock();
		$adapter2->expects(self::once())
			->method('row')
			->with($sql2, $params2, $types2)
			->willReturn($adapter2);

		$sql3    = 'SELECT * FROM table_three';
		$params3 = [];
		$types3  = null;

		$adapter3 = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['row'])
			->getMock();
		$adapter3->expects(self::once())
			->method('row')
			->with($sql3, $params3, $types3)
			->willReturn($adapter3);

		return [
			[$adapter1, $sql1, $params1, $types1],
			[$adapter2, $sql2, $params2, $types2],
			[$adapter3, $sql3, $params3, $types3]
		];
	}

	/**
	 * @dataProvider rowsProvider
	 */
	public function testRows($adapter, $sql, $params, $types): void
	{
		Db::setAdapter($adapter);

		if ($types)
			Db::rows($sql, $params, $types);
		elseif ($params)
			Db::rows($sql, $params);
		else
			Db::rows($sql);
	}

	public function rowsProvider(): array
	{
		$sql1    = 'SELECT * FROM table_one';
		$params1 = [1, 1];
		$types1  = 'is';

		$adapter1 = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['rows'])
			->getMock();
		$adapter1->expects(self::once())
			->method('rows')
			->with($sql1, $params1, $types1)
			->willReturn($adapter1);

		$sql2    = 'SELECT * FROM table_two';
		$params2 = [1, 2];
		$types2  = null;

		$adapter2 = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['rows'])
			->getMock();
		$adapter2->expects(self::once())
			->method('rows')
			->with($sql2, $params2, $types2)
			->willReturn($adapter2);

		$sql3    = 'SELECT * FROM table_three';
		$params3 = [];
		$types3  = null;

		$adapter3 = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['rows'])
			->getMock();
		$adapter3->expects(self::once())
			->method('rows')
			->with($sql3, $params3, $types3)
			->willReturn($adapter3);

		return [
			[$adapter1, $sql1, $params1, $types1],
			[$adapter2, $sql2, $params2, $types2],
			[$adapter3, $sql3, $params3, $types3]
		];
	}

	/**
	 * @dataProvider queryProvider
	 */
	public function testQuery($adapter, $sql, $params, $types): void
	{
		Db::setAdapter($adapter);

		if ($types)
			Db::query($sql, $params, $types);
		elseif ($params)
			Db::query($sql, $params);
		else
			Db::query($sql);
	}

	public function queryProvider(): array
	{
		$sql1    = 'SELECT * FROM table_one';
		$params1 = [1, 1];
		$types1  = 'is';

		$adapter1 = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['query'])
			->getMock();
		$adapter1->expects(self::once())
			->method('query')
			->with($sql1, $params1, $types1)
			->willReturn($adapter1);

		$sql2    = 'SELECT * FROM table_two';
		$params2 = [1, 2];
		$types2  = null;

		$adapter2 = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['query'])
			->getMock();
		$adapter2->expects(self::once())
			->method('query')
			->with($sql2, $params2, $types2)
			->willReturn($adapter2);

		$sql3    = 'SELECT * FROM table_three';
		$params3 = [];
		$types3  = null;

		$adapter3 = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['query'])
			->getMock();
		$adapter3->expects(self::once())
			->method('query')
			->with($sql3, $params3, $types3)
			->willReturn($adapter3);

		return [
			[$adapter1, $sql1, $params1, $types1],
			[$adapter2, $sql2, $params2, $types2],
			[$adapter3, $sql3, $params3, $types3]
		];
	}

	public function testBegin(): void
	{
		$adapter = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['begin'])
			->getMock();
		$adapter->expects(self::once())
			->method('begin')
			->willReturn($adapter);

		Db::setAdapter($adapter);
		Db::begin();
	}

	public function testRollback(): void
	{
		$adapter = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['rollback'])
			->getMock();
		$adapter->expects(self::once())
			->method('rollback')
			->willReturn($adapter);

		Db::setAdapter($adapter);
		Db::rollback();
	}

	public function testCommit(): void
	{
		$adapter = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['commit'])
			->getMock();
		$adapter->expects(self::once())
			->method('commit')
			->willReturn($adapter);

		Db::setAdapter($adapter);
		Db::commit();
	}

	public function testGetLastInsertId(): void
	{
		$adapter = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['getLastInsertId'])
			->getMock();
		$adapter->expects(self::once())
			->method('getLastInsertId')
			->willReturn($adapter);

		Db::setAdapter($adapter);
		Db::getLastInsertId();
	}

	public function testGetFoundRows(): void
	{
		$adapter = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['getFoundRows'])
			->getMock();
		$adapter->expects(self::once())
			->method('getFoundRows')
			->willReturn($adapter);

		Db::setAdapter($adapter);
		Db::getFoundRows();
	}

	public function testEscape(): void
	{
		$expected = 'string';

		$adapter = $this->getMockBuilder(PdoAdapter::class)
			->onlyMethods(['escape'])
			->getMock();
		$adapter->expects(self::once())
			->method('escape')
			->with($expected)
			->willReturn($adapter);

		Db::setAdapter($adapter);
		Db::escape($expected);
	}
}
