<?php
namespace Veles\Tests\Routing;

use PHPUnit\Framework\TestCase;
use Veles\Routing\RouteRegex;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-21 at 18:06:33.
 * @group route
 */
class RouteRegexTest extends TestCase
{
	/**
	 * @var RouteRegex
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp(): void
	{
		$this->object = new RouteRegexChild;
		$this->object::setParams(null);
	}

	/**
	 * @dataProvider checkProvider
	 */
	public function testCheck($pattern, $url, $expected, $params): void
	{
		$result = $this->object->check($pattern, $url);
		$msg = 'Wrong RouteRegex::check() behavior!';
		self::assertSame($expected, $result, $msg);
	}

	public function checkProvider(): array
	{
		return [
			['#^\/article\/(?<id>[\d\w\-]+).html$#', '/article/234.html', true, ['id' => '234']],
			['#^\/article\/(?<id>[\d\w\-]+).html$#', '/article/lal-4.html', true, ['id' => 'lal-4']],
			['#^\/article\/([\d\w\-]+).html$#', '/article/html', false, null],
			['#^\/article\/([\d\w\-]+).html$#', 'index.html', false, null],
			['#^\/article\/([\d\w\-]+).html$#', '/article/lal 4.html', false, null]
		];
	}

	public function testGetParams(): void
	{
		$pattern = '#^\/article\/(?<id>[\d\w\-]+).html$#';
		$url = '/article/234.html';
		$expected = ['id' => '234'];

		$this->object::check($pattern, $url);
		$result = $this->object::getParams();

		$msg = 'RouteRegex::getParams() returns wrong result!';
		self::assertSame($expected, $result, $msg);
	}
}
