<?php
namespace Veles\Tests\Routing;

use PHPUnit\Framework\TestCase;
use Veles\Routing\RouteStatic;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-23 at 06:58:58.
 * @group route
 */
class RouteStaticTest extends TestCase
{
	/**
	 * @var RouteStatic
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp(): void
	{
		$this->object = new RouteStatic;
	}

	/**
	 * @dataProvider checkProvider
	 */
	public function testCheck($pattern, $url, $expected): void
	{
		$result = $this->object::check($pattern, $url);

		$msg = 'RouteStatic::check() returns wrong result!';
		self::assertSame($expected, $result, $msg);
	}

	public function checkProvider(): array
	{
		return [
			['/route/static/', '/route/static/', true],
			['/route/static/', '/route/', false],
			['/index.php', '/index.php', true],
			['/route/static/', '/route/static/index.php', true],
			['/route/static', '/route/static/index.php', true]
		];
	}
}
