<?php
namespace Veles\Tests\Routing;

use PHPUnit\Framework\TestCase;
use Veles\Routing\IniConfigLoader;
use Veles\Routing\RouteBase;
use Veles\Routing\RoutesConfig;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-24 at 17:15:24.
 * @group route
 */
class RouteBaseTest extends TestCase
{
	/** @var  RouteBase */
	protected $object;

	protected function setUp(): void
	{
		$this->object = new RouteBase;
		$config = new RoutesConfig(
			new IniConfigLoader(TEST_DIR . '/Project/routes.ini')
		);
		$this->object->setConfigHandler($config);
	}

	public function testGetConfigHandler(): void
	{
		$routes_loader = new IniConfigLoader(TEST_DIR . '/Project/routes.ini');
		$expected = new RoutesConfig($routes_loader);
		$this->object->setConfigHandler($expected);

		$result = $this->object->getConfigHandler();
		$msg = 'RouteBase::getConfigHandler() returns wrong result!';
		self::assertSame($expected, $result, $msg);
	}
}
