<?php

namespace Veles\Tests\Validators;

use PHPUnit\Framework\TestCase;
use Veles\Validators\Md5Validator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-13 at 20:51:09.
 *
 * @group validators
 */
class Md5ValidatorTest extends TestCase
{
	/**
	 * @var Md5Validator
	 */
	protected $object;

	/**
	 * @dataProvider checkProvider
	 */
	public function testCheck($value, $expected, $caseSensitive): void
	{
		$object = new Md5Validator($caseSensitive);
		$result = $object->check($value);
		$msg    = 'Md5Validator returns wrong result!';
		self::assertSame($expected, $result, $msg);
	}

	public function checkProvider(): array
	{
		return [
			[md5(uniqid()), true, true],
			[sha1(uniqid()), false, false],
		];
	}
}
