<?php
/**
 * Byte values validator
 * @file    NumberValidatorTest.php
 *
 * PHP version 7.1+
 *
 * @author  Alexander Yancharuk <alex at itvault dot info>
 * @date    Вск Фев 17 10:48:43 2013
 * @license The BSD 3-Clause License
 *          <https://tldrlegal.com/license/bsd-3-clause-license-(revised)>.
 */

namespace Veles\Tests\Validators;

use PHPUnit\Framework\TestCase;
use Veles\Validators\NumberValidator;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-24 at 08:30:49.
 * @group validators
 */
class NumberValidatorTest extends TestCase
{
	/**
	 * @group  Validators
	 * @see	   NumberValidator::check()
	 * @dataProvider checkProvider
	 */
	public function testCheck($number, $expected): void
	{
		$object = new NumberValidator;
		$result = $object->check($number);

		$msg = 'Wrong NumberValidator::check() validation';
		self::assertSame($expected, $result, $msg);
	}

	public function checkProvider(): array
	{
		return [
			['lalala', false],
			[34, true],
			['34', true],
			[2147483649, false]
		];
	}
}
