<?php
/**
 * RegEx values validator test
 * @file    RegExValidatorTest.php
 *
 * PHP version 7.1+
 *
 * @author  Alexander Yancharuk <alex at itvault dot info>
 * @date    Вск Фев 17 10:48:43 2013
 * @license The BSD 3-Clause License
 *          <https://tldrlegal.com/license/bsd-3-clause-license-(revised)>.
 */

namespace Veles\Tests\Validators;

use PHPUnit\Framework\TestCase;
use Veles\Validators\RegExValidator;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-26 at 09:40:24.
 * @group validators
 */
class RegExValidatorTest extends TestCase
{
    /**
     * @group Validators
	 * @see RegExValidator::check()
	 * @dataProvider checkProvider
     */
    public function testCheck($pattern, $value, $expected): void
    {
		$object = new RegExValidator($pattern);

		$actual = $object->check($value);

		$msg = 'Wrong RegExValidator::check() validation';
		self::assertSame($expected, $actual, $msg);
    }

	public function checkProvider(): array
	{
		return [
			[
				'/^\/(?:index.html|page\-(\d+)\.html)?$/',
				'/index.html',
				true
			],
			[
				'/^\/(?:index.html|page\-(\d+)\.html)?$/',
				'/page-19.html',
				true
			],
			[
				'/^\/(?:index.html|page\-(\d+)\.html)?$/',
				'/page-1d9.html',
				false
			]
		];
	}

    /**
	 * @group Validators
	 * @see RegExValidator::validate()
	 * @dataProvider validateProvider
     */
    public function testValidate($pattern, $value, $expected): void
    {
		$actual = RegExValidator::validate($pattern, $value);

		$msg = 'Wrong RegExValidator::validate() validation';
		self::assertSame($expected, $actual, $msg);
    }

	public function validateProvider(): array
	{
		return [
			[
				'/^\/(?:index.html|page\-(\d+)\.html)?$/',
				'/index.html',
				true
			],
			[
				'/^\/(?:index.html|page\-(\d+)\.html)?$/',
				'/page-19.html',
				true
			],
			[
				'/^\/(?:index.html|page\-(\d+)\.html)?$/',
				'/page-1d9.html',
				false
			]
		];
	}
}
