<?php
namespace Veles\Tests\Validators;

use PHPUnit\Framework\TestCase;
use Veles\Validators\Sha1Validator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-08 at 18:42:09.
 * @group validators
 */
class Sha1ValidatorTest extends TestCase
{
	/**
	 * @var Sha1Validator
	 */
	protected $object;

	/**
	 * @dataProvider checkProvider
	 */
	public function testCheck($value, $expected, $caseSensitive): void
	{
		$object = new Sha1Validator($caseSensitive);
		$result = $object->check($value);
		$msg = 'Sha1Validator returns wrong result!';
		self::assertSame($expected, $result, $msg);
	}

	public function checkProvider(): array
	{
		return [
			[sha1(uniqid()), true, true],
			[md5(uniqid()), false, false],
		];
	}
}
