<?php
namespace Tests\Validators;

use PHPUnit\Framework\TestCase;
use Veles\Tools\Precision;
use Veles\Validators\TimerPrecisionValidator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-03-05 at 21:13:54.
 * @group validators
 */
class TimerPrecisionValidatorTest extends TestCase
{
    /**
     * @var TimerPrecisionValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new TimerPrecisionValidator;
    }

    /**
     * @covers \Veles\Validators\TimerPrecisionValidator::check
	 * @dataProvider checkProvider
     */
    public function testCheck($value, $expected)
    {
		$actual = $this->object->check($value);
		$msg = 'TimerPrecisionValidator::check() returns wrong values';
		$this->assertSame($expected, $actual, $msg);
    }

	public function checkProvider()
	{
		return [
			[Precision::SECONDS, true],
			[Precision::MILLISECONDS, true],
			[Precision::MICROSECONDS, true],
			[Precision::NANOSECONDS, true],
			[Precision::PICOSECONDS, true],
			[rand(13, PHP_INT_MAX), false]
		];
    }
}
