<?php
namespace Veles\Tests\View\Adapters;

use PHPUnit\Framework\TestCase;
use Veles\View\Adapters\CustomJsonAdapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-08 at 07:14:04.
 *
 * @group view
 */
class CustomJsonAdapterTest extends TestCase
{
	/**
	 * @var CustomJsonAdapter
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp(): void
	{
		$this->object = new CustomJsonAdapter;
	}

	public function testShow(): void
	{
		$expected = '';

		$this->expectOutputString($expected);
		$this->object->show(null);

        $expected = '{"prop":"this is json-string"}';
		$this->object->set($expected);

		$this->expectOutputString($expected);
		$this->object->show(null);
	}

	public function testGet(): void
	{
		$expected = '{"prop":100500}';
		$this->object->set($expected);

		$actual = $this->object->get(null);
		$msg = 'CustomJsonAdapter::show() returns wrong result!';
		self::assertSame($expected, $actual, $msg);
	}

	public function testIsCached(): void
	{
		$expected = false;

		$actual = $this->object->isCached('path');
		$msg = 'CustomJsonAdapter::isCached() returns wrong result!';
		self::assertSame($expected, $actual, $msg);
	}
}
