<?php
namespace Veles\Tests\View\Adapters;

use PHPUnit\Framework\TestCase;
use Veles\View\Adapters\JsonAdapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-16 at 22:44:11.
 * @group view
 */
class JsonAdapterTest extends TestCase
{
	/**
	 * @var JsonAdapter
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp(): void
	{
		$this->object = new JsonAdapter;
	}

	public function testShow(): void
	{
		$this->expectOutputString('');
		$this->object->show(null);

		$vars = ['a', 'b', 'c'];

		$this->object->set($vars);
		$expected = json_encode($vars);
		$this->expectOutputString($expected);
		$this->object->show(null);
	}

	public function testGet(): void
	{
		$vars = ['a', 'b', 'c'];
		$this->object->set($vars);
		$expected = json_encode($vars);
		$result = $this->object->get('');
		$msg = 'Wrong JsonAdapter::get() result!';
		self::assertSame($expected, $result, $msg);
	}

	public function testIsCached(): void
	{
		$expected = false;
		$result = $this->object->isCached('');
		$msg = 'Wrong JsonAdapter::isCached() result!';
		self::assertSame($expected, $result, $msg);
	}
}
