<?php
namespace Veles\Tests\View\Adapters;

use PHPUnit\Framework\TestCase;
use Veles\View\Adapters\NativeAdapter;
use Veles\View\View;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-20 at 17:47:01.
 * @group view
 */
class NativeAdapterTest extends TestCase
{
	/**
	 * @var NativeAdapter
	 */
	protected $object;
	/** @var  string */
	protected $html;
	protected $dir;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp(): void
	{
		$this->object = NativeAdapter::instance();
		$this->dir = TEST_DIR . '/Project/View/';
		$this->html = <<<EOF
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Veles is a fast PHP framework</title>
</head>
<body>
	<div id="main_wrapper">
		la lala!
	</div>
	<div id="footer_wrapper">
		Hello World!
	</div>
</body>
</html>

EOF;
	}

	public function testGetTemplateDir(): void
	{
		$expected = '/templates/dir';
		$this->object->setTemplateDir($expected);

		$actual = $this->object->getTemplateDir();

		$msg = 'Wrong NativeAdapter::getTemplateDir() result!';
		self::assertSame($expected, $actual, $msg);
	}

	public function testShow(): void
	{
		$this->object->setTemplateDir($this->dir);
		$this->object->set(['a' => 'la', 'b' => 'lala', 'c' => 'Hello']);

		$this->expectOutputString($this->html);

		$this->object->show('Frontend/index.phtml');
	}

	public function testGet(): void
	{
		$this->object->setTemplateDir($this->dir);
		$this->object->set(['a' => 'la', 'b' => 'lala', 'c' => 'Hello']);

		$result = $this->object->get('Frontend/index.phtml');
		$msg = 'Wrong NativeAdapter::get() result!';
		self::assertSame($this->html, $result, $msg);
	}

	public function testIsCached(): void
	{
		$expected = false;
		$result = $this->object->isCached('Frontend/index.phtml');

		$msg = 'Wrong NativeAdapter::isCached() result!';
		self::assertSame($expected, $result, $msg);
	}

	public function testConstruct(): void
	{
		NativeAdapterChild::unsetInstance();

		$object = NativeAdapter::instance();
		$object->setTemplateDir(TEST_DIR . '/Project/View/');
		View::setAdapter($object);
		$expected = NativeAdapter::class;

		$msg = 'Wrong NativeAdapter::__construct() behavior!';
		$actual = $object->getDriver();
		self::assertInstanceOf($expected, $actual, $msg);
	}
}
