<?php
namespace Veles\Tests\View\Adapters;

use Veles\View\Adapters\SmartyAdapter;

include_once 'Smarty/Smarty.class.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-08 at 07:47:07.
 */
class SmartyAdapterTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var SmartyAdapter
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new SmartyAdapter;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Veles\View\Adapters\SmartyAdapter::set
	 * @todo   Implement testSet().
	 */
	public function testSet()
	{
		$vars = [
			'variable-1' => 100,
			'variable-2' => 200,
		];

		$resource = $this->getMockBuilder('\Smarty')
			->disableOriginalConstructor()
			->setMethods(['assign'])
			->getMock();
		$resource->expects($this->exactly(2))
			->method('assign')
			->withConsecutive(
				[$this->equalTo(1), $this->equalTo('variable-1'), $this->equalTo(100)],
				[$this->equalTo(2), $this->equalTo('variable-2'), $this->equalTo(200)]
			);

		$this->object->set($vars);
	}

	/**
	 * @covers Veles\View\Adapters\SmartyAdapter::del
	 * @todo   Implement testDel().
	 */
	public function testDel()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\View\Adapters\SmartyAdapter::show
	 * @todo   Implement testShow().
	 */
	public function testShow()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\View\Adapters\SmartyAdapter::get
	 * @todo   Implement testGet().
	 */
	public function testGet()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\View\Adapters\SmartyAdapter::clearCache
	 * @todo   Implement testClearCache().
	 */
	public function testClearCache()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\View\Adapters\SmartyAdapter::clearAllCache
	 * @todo   Implement testClearAllCache().
	 */
	public function testClearAllCache()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\View\Adapters\SmartyAdapter::isCached
	 * @todo   Implement testIsCached().
	 */
	public function testIsCached()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
