<?php
namespace Veles\Tests\View\Adapters;

use PHPUnit\Framework\TestCase;
use Smarty;
use Veles\View\Adapters\SmartyAdapter;

include_once 'Smarty/Smarty.class.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-08 at 07:47:07.
 *
 * @group view
 */
class SmartyAdapterTest extends TestCase
{
	/**
	 * @var SmartyAdapter
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp(): void
	{
		$this->object = new SmartyAdapter;
	}

	public function testSet(): void
	{
		$vars = ['variable-1' => 100, 'variable-2' => 200];

		$driver = $this->getMockBuilder('\Smarty')
			->disableOriginalConstructor()
			->onlyMethods(['assign'])
			->getMock();
		$driver->expects(self::exactly(2))
			->method('assign')
			->withConsecutive(['variable-1', 100], ['variable-2', 200]);

		$this->object->setDriver($driver);
		$this->object->set($vars);
	}

	public function testDel(): void
	{
		$vars = ['variable-1', 'variable-2'];

		$driver = $this->getMockBuilder('\Smarty')
			->disableOriginalConstructor()
			->onlyMethods(['clearAssign'])
			->getMock();
		$driver->expects(self::exactly(2))
			->method('clearAssign')
			->withConsecutive(['variable-1'], ['variable-2']);

		$this->object->setDriver($driver);
		$this->object->del($vars);
	}

	public function testShow(): void
	{
		$path = '/path/to/template';

		$driver = $this->getMockBuilder(Smarty::class)
			->disableOriginalConstructor()
			->onlyMethods(['display'])
			->getMock();
		$driver->expects(self::once())
			->method('display')
			->with($path);

		$this->object->setDriver($driver);
		$this->object->show($path);
	}

	public function testGet(): void
	{
		$path = '/path/to/template';

		$driver = $this->getMockBuilder(Smarty::class)
			->disableOriginalConstructor()
			->onlyMethods(['fetch'])
			->getMock();
		$driver->expects(self::once())
			->method('fetch')
			->with($path);

		$this->object->setDriver($driver);
		$this->object->get($path);
	}

	public function testClearCache(): void
	{
		$path = 'template';

		$driver = $this->getMockBuilder(Smarty::class)
			->disableOriginalConstructor()
			->onlyMethods(['clearCache'])
			->getMock();
		$driver->expects(self::once())
			->method('clearCache')
			->with($path);

		$this->object->setDriver($driver);
		$this->object->clearCache($path);
	}

	public function testClearAllCache(): void
	{
		$expired = 500;

		$driver = $this->getMockBuilder(Smarty::class)
			->disableOriginalConstructor()
			->onlyMethods(['clearAllCache'])
			->getMock();
		$driver->expects(self::exactly(2))
			->method('clearAllCache')
			->withConsecutive([$expired],[null]);

		$this->object->setDriver($driver);
		$this->object->clearAllCache($expired);
		$this->object->clearAllCache();
	}

	public function testIsCached(): void
	{
		$template = 'template';

		$driver = $this->getMockBuilder(Smarty::class)
			->disableOriginalConstructor()
			->onlyMethods(['isCached'])
			->getMock();
		$driver->expects(self::once())
			->method('isCached')
			->with($template);

		$this->object->setDriver($driver);
		$this->object->isCached($template);
	}
}
