<?php
namespace Veles\Tests\Traits;

use PHPUnit\Framework\TestCase;
use Veles\DataBase\Loggers\PdoErrorLogger;
use Veles\ErrorHandler\BaseErrorHandler;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-19 at 18:41:12.
 * @group traits
 */
class ObservableTest extends TestCase
{
	/**
	 * @var BaseErrorHandler
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp(): void
	{
		$this->object = new BaseErrorHandler;
	}

	public function testDetach(): void
	{
		$mock = $this->getMockBuilder(PdoErrorLogger::class)
			->onlyMethods(['update'])
			->getMock();

		$mock->expects(self::never())
			->method('update');

		$this->object->attach($mock);
		$this->object->detach($mock);

		$this->object->notify();
	}

	public function testNotify(): void
	{
		$mock = $this->getMockBuilder(PdoErrorLogger::class)
			->onlyMethods(['update'])
			->getMock();

		$mock->expects(self::once())
			->method('update')
			->with($this->object);

		$this->object->attach($mock);

		$this->object->notify();
	}
}
