<?php
namespace Veles\Tests\Tools;

use PHPUnit\Framework\TestCase;
use RuntimeException;
use Veles\Tools\ModelParams;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-12-07 at 21:23:06.
 * @group tools
 */
class ModelParamsTest extends TestCase
{
	/**
	 * @dataProvider getTypeProvider
	 */
	public function testGetType($type, $expected): void
	{
		$result = ModelParams::getType($type);
		$msg = 'ModelParams::getType() returns wrong result!';
		self::assertSame($expected, $result, $msg);
	}

	public function getTypeProvider(): array
	{
		return [
			['char(20)', 'string'],
			['varchar(20)', 'string'],
			['mediumtext', 'string'],
			['text', 'string'],
			['enum', 'string'],
			['timestamp', 'string'],
			['datetime', 'string'],
			['date', 'string'],
			['time', 'string'],
			['tinyint(10)', 'int'],
			['bit(1)', 'string'],
			['smallint(10)', 'int'],
			['int(10)', 'int'],
			['mediumint(5)', 'int'],
			['bigint(10)', 'int'],
			['decimal(10,0)', 'float'],
			['dec(10,0)', 'float'],
			['float', 'float'],
			['real', 'float'],
			['double', 'float']
		];
	}

	public function testRuntimeException(): void
	{
		$this->expectException(RuntimeException::class);
		$this->expectExceptionMessage('Unknown data type');

		ModelParams::getType('unknown');
	}
}
