<?php
namespace Veles\Tests\Tools;

use PHPUnit\Framework\TestCase;
use Veles\Tools\SnippetBuilder;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-17 at 18:34:34.
 * @group tools
 */
class SnippetBuilderTest extends TestCase
{
	/**
	 * @var SnippetBuilder
	 */
	protected $object;

	public function testBuild(): void
	{
		$expected = <<<EOF
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Veles is a fast PHP framework</title>
</head>
<body>
	<div id="main_wrapper">
		Test complete!
	</div>
	<div id="footer_wrapper">
		Hello World!
	</div>
</body>
</html>

EOF;

		$vars = ['a' => 'Test', 'b' => 'complete', 'c' => 'Hello'];
		$obj = new SnippetBuilder($vars);
		$path = realpath(__DIR__ . '/../Project/View/Frontend/index.phtml');
		$result = $obj->build($path);

		$msg = 'SnippetBuilder::build() returns wrong result!';
		self::assertSame($expected, $result, $msg);
	}
}
