<?php
namespace Veles\Tests\Cache\Adapters;

use Exception;
use PHPUnit\Framework\TestCase;
use Veles\Cache\Adapters\MemcacheRaw;
use Veles\Cache\Cache;

require_once 'fsockopen_stub.php';
require_once 'fclose_stub.php';
require_once 'fgets_stub.php';
require_once 'fwrite_stub.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-23 at 18:02:03.
 * @group memcacheraw
 */
class MemcacheRawTest extends TestCase
{
	protected static $tpl;

	/**
	 * Cache adapter can be reset in other tests
	 */
	public static function setUpBeforeClass()
	{

	}

	public static function tearDownAfterClass()
	{
		//Cache::del(self::$tpl);
	}

	/**
	 * Restore correct memcache settings for next tests
	 */
	public function tearDown()
	{
		//MemcacheRaw::setConnectionParams('localhost', 11211);
	}

	/**
	 * @covers \Veles\Cache\Adapters\MemcacheRaw::__construct

	 */
	public function testConstructor()
	{
		$host = 'VELES_UNIT_TEST';
		$port = rand(10600, 15000);

		$expected = [
			'host' => $host,
			'port' => $port,
			'errno'  => null,
			'errstr' => null
		];

		MemcacheRaw::setConnectionParams($host, $port);

		$object = new MemcacheRawChild;
		$actual = $object->getConnection();

		$msg = 'MemcacheRaw::__construct() wrong behavior';
		$this->assertSame($expected, $actual, $msg);
	}

	/**
	 * @covers \Veles\Cache\Adapters\MemcacheRaw::__construct
	 * @expectedException Exception
	 * @expectedExceptionMessage Can not connect to Memcache. Host: localhost Port: 11213
	 */
	public function testConctructException()
	{
		MemcacheRaw::setConnectionParams('localhost', 11213);

		new MemcacheRawChild;
	}

	/**
	 * @covers \Veles\Cache\Adapters\MemcacheRaw::setConnectionParams
	 */
	public function testSetConnectionParams()
	{
		$host = 'VELES_UNIT_TEST';
		$port = rand(10600, 15000);

		MemcacheRaw::setConnectionParams($host, $port);
		$object = new MemcacheRawChild;

		$actual = $object->getHost();

		$msg = 'Wrong MemcacheRaw::$host result';
		$this->assertSame($host, $actual, $msg);
		$this->assertInternalType('string', $actual, $msg);

		$actual = $object->getPort();

		$msg = 'Wrong MemcacheRaw::$port result';
		$this->assertSame($port, $actual, $msg);
		$this->assertInternalType('integer', $actual, $msg);
	}

	/**
	 * @covers \Veles\Cache\Adapters\MemcacheRaw::disconnect
	 */
	public function testDisconnect()
	{
		$host = 'VELES_UNIT_TEST';
		$port = rand(10600, 15000);
		$errno = $errstr = null;

		$expected_connection = compact('host', 'port', 'errno', 'errstr');

		MemcacheRaw::setConnectionParams($host, $port);
		$object = new MemcacheRawChild;

		$actual = $object->disconnect();

		$msg = 'MemcacheRaw::disconnect() return wrong result!';
		$this->assertSame(true, $actual, $msg);

		$actual = $object->getConnection();

		$msg = 'Wrong type of MemcacheRaw::$connection!';
		$this->assertSame($expected_connection, $actual, $msg);
	}

	/**
	 * @covers \Veles\Cache\Adapters\MemcacheRaw::command
	 */
	public function testCommand()
	{
		$key   = uniqid('VELES::UNIT-TEST::');
		$host  = 'VELES_UNIT_TEST';
		$port  = rand(10600, 15000);

		$expected = true;

		MemcacheRaw::setConnectionParams($host, $port);
		$object = new MemcacheRawChild;

		$actual = $object->command("delete $key");

		$msg = 'MemcacheRaw::command() malfunction!';
		$this->assertSame($expected, $actual, $msg);
	}

	/**
	 * @covers \Veles\Cache\Adapters\MemcacheRaw::getSlabs
	 * @covers \Veles\Cache\Adapters\MemcacheRaw::delByTemplate
	 * @covers \Veles\Cache\Adapters\MemcacheRaw::delete
	 */
	public function testDelByTemplate()
	{
		$host  = 'VELES_UNIT_TEST_DEL_BY_TEMPLATE';
		$port  = rand(10600, 15000);

		MemcacheRaw::setConnectionParams($host, $port);
		$object = new MemcacheRawChild;

		$template = "VELES::UNIT-TEST::59ea1be2795cd::";

		$actual = $object->delByTemplate($template);

		$msg = 'MemcacheRaw::delByTemplate return wrong result!';
		$this->assertTrue($actual instanceof MemcacheRaw, $msg);
	}

	/**
	 * @covers \Veles\Cache\Adapters\MemcacheRaw::query
	 */
	public function testQuery()
	{
		$key   = 'VELES::UNIT-TEST::59ea24a876add';
		$value = '434';
		$host  = 'VELES_UNIT_TEST_QUERY';
		$port  = rand(10600, 15000);

		MemcacheRaw::setConnectionParams($host, $port);
		$object = new MemcacheRawChild;

		$output = $object->query("get $key");
		$expr = "/^VALUE $key [\d\s]+$value\s$/";
		$result = preg_match($expr, $output);

		$msg = 'MemcacheRaw::query return wrong result!';
		$this->assertSame(1, $result, $msg);
	}
}
